# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version from GitHub releases
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=5000"]  # 5MB limit (adjust as needed)
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
