this_semester: "25-ws"
data: "data/data-raw/SoSe25"
# data_23ws: "data/data-raw/23-ws"
# data_24ss: "data/data-raw/24-ss"
data_test: "data/data-raw/test"
# data_out_23ws: "data/data-processed/23-ws"
# data_out_24ss: "data/data-processed/24-ss"
data_out: "data/data-processed"
profile: "?"
data_raw_pattern: ".csv$"
demo: "data/demo"
